version: '3.8'

services:
  GROUP_1_web:
    build: .
    container_name: group1_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - GROUP_1_db

  GROUP_1_db:
    image: mysql:8.0
    container_name: group1_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: healthrwanda
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  GROUP_1_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: group1_phpmyadmin
    environment:
      PMA_HOST: GROUP_1_db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - GROUP_1_db

volumes:
  db_data:
